import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import Navbar from "@/ui/components/Navbar/Navbar";
import Footer from "@/ui/components/Footer/Footer";
import Map from "@/ui/components/Footer/Map";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="light">
          <Navbar />
          <main className="flex-1">{children}</main>
          <Map />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
